### ISSUE TITLE
Consider this reduction:

### ISSUE THREAD

**Issue by acbart** [UD-CISC275-F21/ud-cis-scheduler-team-9#38]
https://github.com/UD-CISC275-F21/ud-cis-scheduler-team-9/blob/59fd7246b816c3b6733a6071aa6adeb87ae0c2ab/src/Components/AddSemesterModal.tsx#L201-L217

```typescript
return Object.values(record).reduce( (totalSoFar: number, course: Course) => totalSoFar + course.credits)
```

**Comment by stonex159** [comment]
I have, Doing as you suggested does seem nicer, but it doesn't work well with our Course interface. Adjusting for that makes it mess up due to how this function is being called and the special way useStates conclude. But I did revise the determineCredits function to be a lot more efficient. I had forgotten about object.values when I originally made it. With that and a simple for loop adder it works far better than before.
